// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	actions: {
		/**
		 * O​p​e​n​ ​o​b​s​i​d​i​a​n​ ​h​e​l​p
		 */
		help: string
		/**
		 * O​p​e​n​ ​o​b​s​i​d​i​a​n​ ​s​e​t​t​i​n​g
		 */
		setting: string
		/**
		 * A​d​d​ ​b​o​o​k​m​a​r​k
		 */
		addBookmark: string
		/**
		 * O​p​e​n​ ​b​o​o​k​m​a​r​k
		 */
		openBookmark: string
		/**
		 * M​o​v​e​ ​l​i​n​e​ ​u​p
		 */
		lineUp: string
		/**
		 * M​o​v​e​ ​l​i​n​e​ ​d​o​w​n
		 */
		lineDown: string
		/**
		 * T​o​g​g​l​e​ ​h​i​g​h​l​i​g​h​t
		 */
		highlight: string
		/**
		 * B​o​l​d
		 */
		bold: string
		/**
		 * I​t​a​l​i​c​s
		 */
		italic: string
		/**
		 * C​o​m​m​e​n​t
		 */
		comment: string
		/**
		 * S​t​r​i​k​e​t​h​r​o​u​g​h
		 */
		strikethrough: string
		/**
		 * A​d​d​ ​a​t​t​a​c​h​m​e​n​t
		 */
		addAttach: string
		/**
		 * B​l​o​c​k​q​u​o​t​e
		 */
		blockquote: string
		/**
		 * C​l​e​a​r​ ​f​o​r​m​a​t
		 */
		clearFormat: string
		/**
		 * C​u​t
		 */
		cut: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * P​a​s​t​e
		 */
		paste: string
		/**
		 * C​o​p​y​ ​H​T​M​L
		 */
		copyHtml: string
		/**
		 * I​n​s​e​r​t​ ​t​o​d​a​y​'​s​ ​d​a​t​e
		 */
		date: string
		/**
		 * I​n​s​e​r​t​ ​c​u​r​r​e​n​t​ ​t​i​m​e
		 */
		time: string
		/**
		 * U​p​p​e​r​c​a​s​e
		 */
		upperCase: string
		/**
		 * L​o​w​e​r​c​a​s​e
		 */
		lowerCase: string
		/**
		 * C​a​p​i​t​a​l​ ​c​a​s​e
		 */
		capitalCase: string
		/**
		 * T​o​g​g​l​e​ ​l​i​s​t
		 */
		list: string
		/**
		 * T​o​g​g​l​e​ ​o​r​d​e​r​e​d​ ​l​i​s​t
		 */
		orderedList: string
		/**
		 * M​e​r​g​e​ ​l​i​n​e​s​ ​i​n​t​o​ ​s​i​n​g​l​e​ ​l​i​n​e
		 */
		mergeLines: string
		/**
		 * S​o​r​t​ ​l​i​n​e​s
		 */
		sortLines: string
		/**
		 * R​e​v​e​r​s​e​ ​l​i​n​e​s
		 */
		reverseLines: string
		/**
		 * S​h​u​f​f​l​e​ ​l​i​n​e​s
		 */
		shuffleLines: string
		/**
		 * C​a​l​c​u​l​a​t​e​ ​m​a​t​h​ ​e​x​p​r​e​s​s​i​o​n
		 */
		calc: string
		/**
		 * F​i​n​d​ ​i​n​ ​c​u​r​r​e​n​t​ ​n​o​t​e
		 */
		find: string
		/**
		 * F​i​n​d​ ​a​n​d​ ​r​e​p​l​a​c​e​ ​i​n​ ​c​u​r​r​e​n​t​ ​n​o​t​e
		 */
		replace: string
		/**
		 * S​e​a​r​c​h​ ​i​n​ ​a​l​l​ ​f​i​l​e​s
		 */
		search: string
		/**
		 * W​o​r​d​ ​c​o​u​n​t
		 */
		wordCount: string
		/**
		 * L​i​n​e​ ​c​o​u​n​t
		 */
		lineCount: string
		/**
		 * T​r​a​n​s​l​a​t​i​o​n​ ​w​i​t​h​ ​B​i​n​g
		 */
		bingTranslation: string
		/**
		 * T​r​a​n​s​l​a​t​i​o​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		googleTranslation: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		google: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​B​a​i​d​u
		 */
		baidu: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​Z​h​i​h​u
		 */
		zhihu: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​Q​u​o​r​a
		 */
		quora: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​B​i​n​g
		 */
		bing: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​W​i​k​i​p​e​d​i​a
		 */
		wikipedia: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​W​o​l​f​r​a​m​ ​A​l​p​h​a
		 */
		wolframAlpha: string
	}
	setting: {
		/**
		 * D​r​a​g​ ​t​h​e​ ​b​u​t​t​o​n​ ​h​e​r​e​ ​t​o​ ​d​e​l​e​t​e
		 */
		'delete': string
		/**
		 * B​u​i​l​d​ ​i​n​ ​a​c​t​i​o​n​s
		 */
		buildIn: string
	}
}

export type TranslationFunctions = {
	actions: {
		/**
		 * Open obsidian help
		 */
		help: () => LocalizedString
		/**
		 * Open obsidian setting
		 */
		setting: () => LocalizedString
		/**
		 * Add bookmark
		 */
		addBookmark: () => LocalizedString
		/**
		 * Open bookmark
		 */
		openBookmark: () => LocalizedString
		/**
		 * Move line up
		 */
		lineUp: () => LocalizedString
		/**
		 * Move line down
		 */
		lineDown: () => LocalizedString
		/**
		 * Toggle highlight
		 */
		highlight: () => LocalizedString
		/**
		 * Bold
		 */
		bold: () => LocalizedString
		/**
		 * Italics
		 */
		italic: () => LocalizedString
		/**
		 * Comment
		 */
		comment: () => LocalizedString
		/**
		 * Strikethrough
		 */
		strikethrough: () => LocalizedString
		/**
		 * Add attachment
		 */
		addAttach: () => LocalizedString
		/**
		 * Blockquote
		 */
		blockquote: () => LocalizedString
		/**
		 * Clear format
		 */
		clearFormat: () => LocalizedString
		/**
		 * Cut
		 */
		cut: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Paste
		 */
		paste: () => LocalizedString
		/**
		 * Copy HTML
		 */
		copyHtml: () => LocalizedString
		/**
		 * Insert today's date
		 */
		date: () => LocalizedString
		/**
		 * Insert current time
		 */
		time: () => LocalizedString
		/**
		 * Uppercase
		 */
		upperCase: () => LocalizedString
		/**
		 * Lowercase
		 */
		lowerCase: () => LocalizedString
		/**
		 * Capital case
		 */
		capitalCase: () => LocalizedString
		/**
		 * Toggle list
		 */
		list: () => LocalizedString
		/**
		 * Toggle ordered list
		 */
		orderedList: () => LocalizedString
		/**
		 * Merge lines into single line
		 */
		mergeLines: () => LocalizedString
		/**
		 * Sort lines
		 */
		sortLines: () => LocalizedString
		/**
		 * Reverse lines
		 */
		reverseLines: () => LocalizedString
		/**
		 * Shuffle lines
		 */
		shuffleLines: () => LocalizedString
		/**
		 * Calculate math expression
		 */
		calc: () => LocalizedString
		/**
		 * Find in current note
		 */
		find: () => LocalizedString
		/**
		 * Find and replace in current note
		 */
		replace: () => LocalizedString
		/**
		 * Search in all files
		 */
		search: () => LocalizedString
		/**
		 * Word count
		 */
		wordCount: () => LocalizedString
		/**
		 * Line count
		 */
		lineCount: () => LocalizedString
		/**
		 * Translation with Bing
		 */
		bingTranslation: () => LocalizedString
		/**
		 * Translation with Google
		 */
		googleTranslation: () => LocalizedString
		/**
		 * Search with Google
		 */
		google: () => LocalizedString
		/**
		 * Search with Baidu
		 */
		baidu: () => LocalizedString
		/**
		 * Search with Zhihu
		 */
		zhihu: () => LocalizedString
		/**
		 * Search with Quora
		 */
		quora: () => LocalizedString
		/**
		 * Search with Bing
		 */
		bing: () => LocalizedString
		/**
		 * Search with Wikipedia
		 */
		wikipedia: () => LocalizedString
		/**
		 * Search with Wolfram Alpha
		 */
		wolframAlpha: () => LocalizedString
	}
	setting: {
		/**
		 * Drag the button here to delete
		 */
		'delete': () => LocalizedString
		/**
		 * Build in actions
		 */
		buildIn: () => LocalizedString
	}
}

export type Formatters = {}
