// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * I​n​v​a​l​i​d​ ​Y​A​M​L​ ​f​o​r​m​a​t​.
	 */
	invalid: string
}

export type TranslationFunctions = {
	/**
	 * Invalid YAML format.
	 */
	invalid: () => LocalizedString
}

export type Formatters = {}
