// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	actions: {
		/**
		 * O​p​e​n​ ​h​e​l​p
		 */
		help: string
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g
		 */
		setting: string
		/**
		 * A​d​d​ ​b​o​o​k​m​a​r​k
		 */
		addBookmark: string
		/**
		 * O​p​e​n​ ​b​o​o​k​m​a​r​k
		 */
		openBookmark: string
		/**
		 * M​o​v​e​ ​l​i​n​e​ ​u​p
		 */
		lineUp: string
		/**
		 * M​o​v​e​ ​l​i​n​e​ ​d​o​w​n
		 */
		lineDown: string
		/**
		 * T​o​g​g​l​e​ ​h​i​g​h​l​i​g​h​t
		 */
		highlight: string
		/**
		 * B​o​l​d
		 */
		bold: string
		/**
		 * I​t​a​l​i​c​s
		 */
		italic: string
		/**
		 * C​o​m​m​e​n​t
		 */
		comment: string
		/**
		 * S​t​r​i​k​e​t​h​r​o​u​g​h
		 */
		strikethrough: string
		/**
		 * A​d​d​ ​a​t​t​a​c​h​m​e​n​t
		 */
		addAttach: string
		/**
		 * B​l​o​c​k​q​u​o​t​e
		 */
		blockquote: string
		/**
		 * C​l​e​a​r​ ​f​o​r​m​a​t
		 */
		clearFormat: string
		/**
		 * C​u​t
		 */
		cut: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * P​a​s​t​e
		 */
		paste: string
		/**
		 * C​o​p​y​ ​H​T​M​L
		 */
		copyHtml: string
		/**
		 * I​n​s​e​r​t​ ​t​o​d​a​y​'​s​ ​d​a​t​e
		 */
		date: string
		/**
		 * I​n​s​e​r​t​ ​c​u​r​r​e​n​t​ ​t​i​m​e
		 */
		time: string
		/**
		 * U​p​p​e​r​c​a​s​e
		 */
		upperCase: string
		/**
		 * L​o​w​e​r​c​a​s​e
		 */
		lowerCase: string
		/**
		 * C​a​p​i​t​a​l​ ​c​a​s​e
		 */
		capitalCase: string
		/**
		 * T​o​g​g​l​e​ ​l​i​s​t
		 */
		list: string
		/**
		 * T​o​g​g​l​e​ ​o​r​d​e​r​e​d​ ​l​i​s​t
		 */
		orderedList: string
		/**
		 * M​e​r​g​e​ ​l​i​n​e​s​ ​i​n​t​o​ ​s​i​n​g​l​e​ ​l​i​n​e
		 */
		mergeLines: string
		/**
		 * S​o​r​t​ ​l​i​n​e​s
		 */
		sortLines: string
		/**
		 * R​e​v​e​r​s​e​ ​l​i​n​e​s
		 */
		reverseLines: string
		/**
		 * S​h​u​f​f​l​e​ ​l​i​n​e​s
		 */
		shuffleLines: string
		/**
		 * C​a​l​c​u​l​a​t​e​ ​m​a​t​h​ ​e​x​p​r​e​s​s​i​o​n
		 */
		calc: string
		/**
		 * F​i​n​d​ ​i​n​ ​c​u​r​r​e​n​t​ ​n​o​t​e
		 */
		find: string
		/**
		 * F​i​n​d​ ​a​n​d​ ​r​e​p​l​a​c​e​ ​i​n​ ​c​u​r​r​e​n​t​ ​n​o​t​e
		 */
		replace: string
		/**
		 * S​e​a​r​c​h​ ​i​n​ ​a​l​l​ ​f​i​l​e​s
		 */
		search: string
		/**
		 * W​o​r​d​ ​c​o​u​n​t
		 */
		wordCount: string
		/**
		 * L​i​n​e​ ​c​o​u​n​t
		 */
		lineCount: string
		/**
		 * T​r​a​n​s​l​a​t​i​o​n​ ​w​i​t​h​ ​B​i​n​g
		 */
		bingTranslation: string
		/**
		 * T​r​a​n​s​l​a​t​i​o​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		googleTranslation: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		google: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​B​a​i​d​u
		 */
		baidu: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​Z​h​i​h​u
		 */
		zhihu: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​Q​u​o​r​a
		 */
		quora: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​B​i​n​g
		 */
		bing: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​W​i​k​i​p​e​d​i​a
		 */
		wikipedia: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​W​o​l​f​r​a​m​ ​A​l​p​h​a
		 */
		wolframAlpha: string
		/**
		 * S​e​a​r​c​h​ ​w​i​t​h​ ​D​u​c​k​D​u​c​k​G​o
		 */
		duckduckgo: string
	}
	setting: {
		/**
		 * D​r​a​g​ ​t​h​e​ ​b​u​t​t​o​n​ ​h​e​r​e​ ​t​o​ ​d​e​l​e​t​e
		 */
		'delete': string
		/**
		 * B​u​i​l​d​i​n​ ​a​c​t​i​o​n​s
		 */
		buildIn: string
		/**
		 * C​u​s​t​o​m​ ​a​c​t​i​o​n​s
		 */
		custom: string
		/**
		 * A​d​d​ ​c​u​s​t​o​m​ ​a​c​t​i​o​n
		 */
		add: string
		/**
		 * D​i​v​i​d​e​r
		 */
		divider: string
		/**
		 * U​p​l​o​a​d
		 */
		upload: string
		/**
		 * A​d​d​ ​c​u​s​t​o​m​ ​a​c​t​i​o​n
		 */
		customTitle: string
		/**
		 * A​ ​c​u​s​t​o​m​ ​a​c​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​a​d​d​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		addSuccess: string
		/**
		 * S​o​u​r​c​e​ ​p​l​u​g​i​n​:​ 
		 */
		plugin: string
		/**
		 * C​o​m​m​a​n​d​:​ 
		 */
		command: string
		/**
		 * I​c​o​n​:​ 
		 */
		icon: string
		/**
		 * N​o​ ​c​u​s​t​o​m​ ​a​c​t​i​o​n​s​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.​ ​Y​o​u​ ​c​a​n​ ​a​d​d​ ​t​h​e​m​ ​u​s​i​n​g​ ​t​h​e​ ​f​o​r​m​ ​b​e​l​o​w​.
		 */
		empty: string
		/**
		 * D​i​s​a​b​l​e​ ​t​h​e​ ​s​y​s​t​e​m​ ​t​o​o​l​b​a​r​ ​w​h​e​n​ ​s​e​l​e​c​t​i​n​g​ ​t​e​x​t
		 */
		disableNativeToolbar: string
		/**
		 * O​n​l​y​ ​s​h​o​w​ ​P​o​p​k​i​t​ ​w​h​e​n​ ​s​e​l​e​c​t​i​n​g​ ​t​e​x​t​ ​w​i​t​h​ ​m​o​u​s​e
		 */
		mouseSelectionOnly: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​.
		 */
		noResult: string
		/**
		 * P​l​e​a​s​e​ ​p​i​c​k​ ​a​n​ ​i​t​e​m​.​.​.
		 */
		pickItem: string
		/**
		 * A​c​t​i​o​n​ ​T​y​p​e
		 */
		actionType: string
		/**
		 * C​h​o​o​s​e​ ​h​o​w​ ​t​h​e​ ​a​c​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​e​x​e​c​u​t​e​d
		 */
		actionTypeDesc: string
		/**
		 * C​o​m​m​a​n​d
		 */
		commandType: string
		/**
		 * E​x​e​c​u​t​e​ ​a​n​ ​O​b​s​i​d​i​a​n​ ​c​o​m​m​a​n​d
		 */
		commandTypeDesc: string
		/**
		 * H​o​t​k​e​y
		 */
		hotkeyType: string
		/**
		 * T​r​i​g​g​e​r​ ​a​ ​k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t
		 */
		hotkeyTypeDesc: string
		/**
		 * C​u​s​t​o​m​ ​C​o​d​e
		 */
		handlerType: string
		/**
		 * E​x​e​c​u​t​e​ ​c​u​s​t​o​m​ ​J​a​v​a​S​c​r​i​p​t​ ​c​o​d​e
		 */
		handlerTypeDesc: string
		/**
		 * H​o​t​k​e​y​ ​A​c​t​i​o​n
		 */
		hotkeyAction: string
		/**
		 * C​u​s​t​o​m​ ​C​o​d​e​ ​A​c​t​i​o​n
		 */
		customHandler: string
	}
}

export type TranslationFunctions = {
	actions: {
		/**
		 * Open help
		 */
		help: () => LocalizedString
		/**
		 * Open setting
		 */
		setting: () => LocalizedString
		/**
		 * Add bookmark
		 */
		addBookmark: () => LocalizedString
		/**
		 * Open bookmark
		 */
		openBookmark: () => LocalizedString
		/**
		 * Move line up
		 */
		lineUp: () => LocalizedString
		/**
		 * Move line down
		 */
		lineDown: () => LocalizedString
		/**
		 * Toggle highlight
		 */
		highlight: () => LocalizedString
		/**
		 * Bold
		 */
		bold: () => LocalizedString
		/**
		 * Italics
		 */
		italic: () => LocalizedString
		/**
		 * Comment
		 */
		comment: () => LocalizedString
		/**
		 * Strikethrough
		 */
		strikethrough: () => LocalizedString
		/**
		 * Add attachment
		 */
		addAttach: () => LocalizedString
		/**
		 * Blockquote
		 */
		blockquote: () => LocalizedString
		/**
		 * Clear format
		 */
		clearFormat: () => LocalizedString
		/**
		 * Cut
		 */
		cut: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Paste
		 */
		paste: () => LocalizedString
		/**
		 * Copy HTML
		 */
		copyHtml: () => LocalizedString
		/**
		 * Insert today's date
		 */
		date: () => LocalizedString
		/**
		 * Insert current time
		 */
		time: () => LocalizedString
		/**
		 * Uppercase
		 */
		upperCase: () => LocalizedString
		/**
		 * Lowercase
		 */
		lowerCase: () => LocalizedString
		/**
		 * Capital case
		 */
		capitalCase: () => LocalizedString
		/**
		 * Toggle list
		 */
		list: () => LocalizedString
		/**
		 * Toggle ordered list
		 */
		orderedList: () => LocalizedString
		/**
		 * Merge lines into single line
		 */
		mergeLines: () => LocalizedString
		/**
		 * Sort lines
		 */
		sortLines: () => LocalizedString
		/**
		 * Reverse lines
		 */
		reverseLines: () => LocalizedString
		/**
		 * Shuffle lines
		 */
		shuffleLines: () => LocalizedString
		/**
		 * Calculate math expression
		 */
		calc: () => LocalizedString
		/**
		 * Find in current note
		 */
		find: () => LocalizedString
		/**
		 * Find and replace in current note
		 */
		replace: () => LocalizedString
		/**
		 * Search in all files
		 */
		search: () => LocalizedString
		/**
		 * Word count
		 */
		wordCount: () => LocalizedString
		/**
		 * Line count
		 */
		lineCount: () => LocalizedString
		/**
		 * Translation with Bing
		 */
		bingTranslation: () => LocalizedString
		/**
		 * Translation with Google
		 */
		googleTranslation: () => LocalizedString
		/**
		 * Search with Google
		 */
		google: () => LocalizedString
		/**
		 * Search with Baidu
		 */
		baidu: () => LocalizedString
		/**
		 * Search with Zhihu
		 */
		zhihu: () => LocalizedString
		/**
		 * Search with Quora
		 */
		quora: () => LocalizedString
		/**
		 * Search with Bing
		 */
		bing: () => LocalizedString
		/**
		 * Search with Wikipedia
		 */
		wikipedia: () => LocalizedString
		/**
		 * Search with Wolfram Alpha
		 */
		wolframAlpha: () => LocalizedString
		/**
		 * Search with DuckDuckGo
		 */
		duckduckgo: () => LocalizedString
	}
	setting: {
		/**
		 * Drag the button here to delete
		 */
		'delete': () => LocalizedString
		/**
		 * Buildin actions
		 */
		buildIn: () => LocalizedString
		/**
		 * Custom actions
		 */
		custom: () => LocalizedString
		/**
		 * Add custom action
		 */
		add: () => LocalizedString
		/**
		 * Divider
		 */
		divider: () => LocalizedString
		/**
		 * Upload
		 */
		upload: () => LocalizedString
		/**
		 * Add custom action
		 */
		customTitle: () => LocalizedString
		/**
		 * A custom action has been added successfully
		 */
		addSuccess: () => LocalizedString
		/**
		 * Source plugin: 
		 */
		plugin: () => LocalizedString
		/**
		 * Command: 
		 */
		command: () => LocalizedString
		/**
		 * Icon: 
		 */
		icon: () => LocalizedString
		/**
		 * No custom actions available yet. You can add them using the form below.
		 */
		empty: () => LocalizedString
		/**
		 * Disable the system toolbar when selecting text
		 */
		disableNativeToolbar: () => LocalizedString
		/**
		 * Only show Popkit when selecting text with mouse
		 */
		mouseSelectionOnly: () => LocalizedString
		/**
		 * No results.
		 */
		noResult: () => LocalizedString
		/**
		 * Please pick an item...
		 */
		pickItem: () => LocalizedString
		/**
		 * Action Type
		 */
		actionType: () => LocalizedString
		/**
		 * Choose how the action will be executed
		 */
		actionTypeDesc: () => LocalizedString
		/**
		 * Command
		 */
		commandType: () => LocalizedString
		/**
		 * Execute an Obsidian command
		 */
		commandTypeDesc: () => LocalizedString
		/**
		 * Hotkey
		 */
		hotkeyType: () => LocalizedString
		/**
		 * Trigger a keyboard shortcut
		 */
		hotkeyTypeDesc: () => LocalizedString
		/**
		 * Custom Code
		 */
		handlerType: () => LocalizedString
		/**
		 * Execute custom JavaScript code
		 */
		handlerTypeDesc: () => LocalizedString
		/**
		 * Hotkey Action
		 */
		hotkeyAction: () => LocalizedString
		/**
		 * Custom Code Action
		 */
		customHandler: () => LocalizedString
	}
}

export type Formatters = {}
